### ISSUE TITLE
Any plans to publish your ssh module?

### ISSUE THREAD

**Issue by tullis** [GregSutcliffe/puppet-modules#1]
Hello,

I'm hoping to use your ssh module with our foreman installation.
Unfortunately, as it's not contained within a repository of its own I can't simply add it to a Puppetfile and have r10k manage it.

Do you have any plans to publish it to the puppet forge, or would you consider putting it in its own Github repository? I know that I can simply copy your code into my own repository, but I thought I'd post this issue first, just in case.

Many thanks.

**Comment by GregSutcliffe** [comment]
If you mean the ssh key management stuff, it's in https://github.com/GregSutcliffe/puppet-ssh_statickeys. If you're managing the SSH daemon itself, I'd suggest any of the many modules in the Puppet forge.

**Comment by tullis** [comment]
Thanks for the quick reply. I meant the ssh key management stuff, so that I can redeploy servers without their host keys changing. I missed your other repository, so apologies for troubling you.
