### ISSUE TITLE
improvements for the ssh module

### ISSUE THREAD

**Issue by hboetes** [GregSutcliffe/puppet-modules#2]
Hi there,

Here is a sloppy patch that fixes/changes a few things. Feel free to cherry pick what you like:
- Change name to more descriptive ssh_settings
- enable rsa,dsa,ecdsa and ed25519 keytypes
- Set the dsa code to 1024
TODO:
- Return a human readable error in case of a problem? For example if the target dir is unwriteable.
- Set up a config variable for the destination path of the keys.

[diff.txt](https://github.com/GregSutcliffe/puppet-modules/files/845508/diff.txt)

**Comment by GregSutcliffe** [comment]
Thanks! this actually lives in its own repo now (https://github.com/GregSutcliffe/puppet-ssh_statickeys) but I'll see about porting it, unless you want to open an issue there :P

**Comment by hboetes** [comment]
Hi Greg,

I created a pull request, like I should.

Cheers,
Han
